config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'bots#index'
  resources :bots, except: [:index]
  resources :triggerphrases, except: [:destroy, :create]
  resources :nodes, except: [:new, :update, :destroy]
  resources :messages, except: [:new, :create, :destroy]
  mount Ckeditor::Engine => '/ckeditor'
  get '/welcome/ckeditor', to: 'welcome#ckeditor_config', as: 'ckeditor_config'
  post 'nodes/usermessage/nodes_message_attach_media', to: 'nodes#nodes_message_attach_media', as: 'nodes_message_attach_media'
  get '/nodes/bot_node_name_edit_icon_click/:id', to: 'nodes#bot_node_name_edit_icon_click', as: 'bot_node_name_edit_icon_click'
  get '/nodes/botnodename/:id', to: 'nodes#bot_node_name', as: 'bot_node_name'
  get '/bots/change/botsettings/:id/:settings_change', to: 'bots#settings_change', as: 'settings_change'
  delete '/reminders/delete/botsettings/:id', to: 'reminders#delete_botsettings', as: 'reminders_delete_botsettings'
  get '/reminders/update/botsettings/:id', to: 'reminders#update_botsettings', as: 'reminders_update_botsettings'
  get '/reminders/create/botsettings/:id', to: 'reminders#create_botsettings', as: 'reminders_create_botsettings'
  get '/triggerphrases/create/botsettings/:id', to: 'triggerphrases#create_botsettings', as: 'triggerphrase_create_botsettings'
  get '/triggerphrases/destroy/botsettings/:id', to: 'triggerphrases#destroy_botsettings', as: 'triggerphrase_destroy_botsettings'
  get '/nodes/transfer_message_toggle_switch/:id', to: 'nodes#transfer_message_toggle_switch', as: 'transfer_message_toggle_switch'
  get '/nodes/exit_message_toggle_switch/:id', to: 'nodes#exit_message_toggle_switch', as: 'exit_message_toggle_switch'
  delete '/messages/user_child_delete_message/:id', to: 'messages#user_child_delete_message', as: 'user_child_delete_message'
  post '/messages/user_child_node_new_message/:id', to: 'messages#user_child_node_new_message', as: 'user_child_node_new_message'
  get '/nodes/user_child_node_compressed_expand/:id', to: 'nodes#user_child_node_compressed_expand', as: 'user_child_node_compressed_expand'
  delete '/nodes/user_child_node_compressed_delete/:id', to: 'nodes#user_child_node_compressed_delete', as: 'user_child_node_compressed_delete'
  post '/nodes/user_child_node_settings/:id', to: 'nodes#user_child_node_settings', as: 'user_child_node_settings'
  delete '/nodes/user_child_node_delete/:id', to: 'nodes#user_child_node_delete', as: 'user_child_node_delete'
  get '/nodes/user_child_node_name_edit_icon_click/:id', to: 'nodes#user_child_node_name_edit_icon_click', as: 'user_child_node_name_edit_icon_click'
  post '/nodes/user_child_node_name_update/:id', to: 'nodes#user_child_node_name_update', as: 'user_child_node_name_update'
  get '/nodes/define_child_node/:id', to: 'nodes#define_child_node', as: 'define_child_node'
  delete '/nodes/child/:id/:parent_id/:bot_id', to: 'nodes#delete_child_nodes', as: 'delete_child_nodes'
  post '/nodes/child_nodes/:node_id/:bot_id', to: 'nodes#add_child_nodes', as: 'add_child_nodes'
  get '/nodes/child_plus/:node_id/:bot_id', to: 'nodes#plus', as: 'node_plus'
  get '/nodes/child_minus/:node_id/:bot_id', to: 'nodes#minus', as: 'node_minus'
  delete '/nodes/node_destroy/:id/:bot_id', to: 'nodes#destroy', as: 'node_destroy'
  get '/nodes/node_expand/:node_id/:bot_id', to: 'nodes#expand', as: 'node_expand'
  put '/nodes/node_update/:node_id/:bot_id', to: 'nodes#update', as: 'node_update'
  post '/messages/edit_message_click/:node_id/:bot_id/:id', to: 'messages#edit_click', as: 'messages_edit_click'
  post '/messages/edit_message/:node_id/:bot_id/:id', to: 'messages#edit', as: 'messages_edit'
  post '/messages/destroy_message/:node_id/:bot_id/:id', to: 'messages#destroy', as: 'messages_destroy'
  post '/messages/new_message/:node_id/:bot_id', to: 'messages#new', as: 'messages_new'
  get '/nodes/new/bot/:node_type/:bot_id/:parent_id', to: 'nodes#new', as: 'new_bot_node'
  get '/triggerphrases/create/:id', to: 'triggerphrases#create', as: 'triggerphrase_create'
  get '/triggerphrases/destroy/:id/:bot_id', to: 'triggerphrases#destroy', as: 'triggerphrase_destroy'
  get '/composemessage/:id', to: 'bots#composemessage', as: 'composemessage'
  get '/activatebot/:id', to: 'bots#activatebot', as: 'activatebot'
  get '/statistics/:id', to: 'bots#statistics', as: 'statistics'
  get '/test/:id', to: 'bots#test', as: 'test'
  get '/updateactive/:id', to: 'welcome#updateactive', as: 'updateactive'
end

app/models/bot.rb
class Bot < ApplicationRecord
  belongs_to :user
  has_many :triggerphrases, dependent: :destroy
  has_many :nodes, dependent: :destroy
  has_many :reminders, dependent: :destroy
end    

app/controllers/bots_controller.rb
class BotsController < ApplicationController

    def index
       @bots = Bot.where(user_id: current_user.id)  
    end    

    def show

    end    

    def new
       @bot = Bot.new
    end
    
    def create
       @bot = Bot.new(params.require(:bot).permit(:name).merge(user_id: current_user.id))
       if @bot.save          
            redirect_to edit_bot_path(@bot.id)
       else
            flash[:alert]  = "A bot with same name already exists"
            redirect_to edit_bot_path(@bot.id)   
       end      
    end    

    def edit
       @bot = Bot.find(params[:id])
       @bots = Bot.where(user_id: current_user.id)
    end
    
    def update
      @bot = Bot.find(params[:id])
      if params[:botsettingsphone]
         number = (params[:botsettingsphone][:phone]).to_i()
         @bot.update(phone: number)
         respond_to do |format|
            format.js
         end
      end  
      if params[:botsettingslanguage]
         if params[:button] == params[:botsettingslanguage][:English] 
            @bot.update(language: params[:botsettingslanguage][:English])
         elsif params[:button] == params[:botsettingslanguage][:Hindi] 
            @bot.update(language: params[:botsettingslanguage][:Hindi])
         elsif params[:button] == params[:botsettingslanguage][:Tamil] 
            @bot.update(language: params[:botsettingslanguage][:Tamil]) 
         end     
         respond_to do |format|
            format.js
         end
      end  
      if params[:botsettingsstarter]
         if params[:button] == params[:botsettingsstarter][:Customer] 
            @bot.update(initconv: params[:botsettingsstarter][:Customer])
         elsif  params[:button] == params[:botsettingsstarter][:Bot] 
            @bot.update(initconv: params[:botsettingsstarter][:Bot])
         end   
         respond_to do |format|
            format.js
         end
      end 
      if params[:botsettingstrigger]
         if params[:button] == params[:botsettingstrigger][:Default] 
            @bot.update(triggerpoint: params[:botsettingstrigger][:Default] )
            if Triggerphrase.where(bot_id: @bot.id)
               for phrase in Triggerphrase.where(bot_id: @bot.id)
                 phrase.destroy
               end   
            end   
         elsif  params[:button] == params[:botsettingstrigger][:Trigger] 
            @bot.update(triggerpoint: params[:botsettingstrigger][:Trigger] )
         end   
         respond_to do |format|
            format.js
         end
      end  

      if params[:setreminder]
         if params[:button] == params[:setreminder][:yes] 
            @bot.update(reminder: params[:setreminder][:yes] )   
         elsif  params[:button] == params[:setreminder][:no] 
            @bot.update(reminder: params[:setreminder][:no] )
            if Reminder.where(bot_id: @bot.id)
               for reminder in Reminder.where(bot_id: @bot.id)
                 reminder.destroy
               end   
            end   
         end   
         respond_to do |format|
            format.js
         end
      end  

      if params[:conversation]
         if params[:button] == params[:conversation][:open] 
            @bot.update(conversation: params[:conversation][:open] )   
         elsif  params[:button] == params[:conversation][:close] 
            @bot.update(conversation: params[:conversation][:close])
         end   
         respond_to do |format|
            format.js
         end
      end  
   
      if params[:botname]
         if @bot.update(params.require(:botname).permit(:name))
            respond_to do |format|
               format.js
            end
         end   
      end   
     
    end    

   def destroy
      @bot = Bot.find(params[:id])
      @bot.destroy
      redirect_to root_path
   end 

   def composemessage
      @bot = Bot.find(params[:id])
      @node = Node.where(bot_id: @bot.id).first
   end
   
   def activatebot
      @bot = Bot.find(params[:id])
   end

   def statistics
      @bot = Bot.find(params[:id]) 
   end   
     
   def test
      @bot = Bot.find(params[:id])
   end

   def settings_change
      @bot = Bot.find(params[:id])
      if (params[:settings_change] == "1")
         respond_to do |format|
            format.js
         end
      end

      if (params[:settings_change] == "2")
         respond_to do |format|
            format.js
         end
      end

      if (params[:settings_change] == "3")
         respond_to do |format|
            format.js
         end
      end

      if (params[:settings_change] == "4")
         respond_to do |format|
            format.js
         end
      end

      if (params[:settings_change] == "5")
         respond_to do |format|
            format.js
         end
      end
      
      if (params[:settings_change] == "reminder")
         respond_to do |format|
            format.js
         end
      end

      if (params[:settings_change] == "anotherreminder")
         respond_to do |format|
            format.js
         end
      end

      if (params[:settings_change] == "skip")
         respond_to do |format|
            format.js
         end
      end
   end   

end

app/helpers/bots_helper.rb
module BotsHelper
end

app/views/bots/_Conversationstarter.html.erb
<a style = "color: #7e7e7e">Conversation Starter</a>
<%= link_to " Change", settings_change_path(@bot.id, "3"), method: :get,style: "margin-left: 30%; color: #157e4b; font-weight: 500; text-decoration: none" , remote: true %>
<%= @bot.initconv %>
<br><br>

app/views/bots/_NoCustomerResponse.html.erb
<a style = "color: #7e7e7e;" >When no customer response</a>
<%= link_to " Change", settings_change_path(@bot.id, "5"), method: :get,style: "margin-left: 10%; color: #157e4b; font-weight: 500; text-decoration: none;" , remote: true %>
<br>
<% i =1 %>
<div class = "mb-4 ml-0 p-0 container" style = "height: 70px; overflow-y: auto;" id = "style-4">
    <% for reminder in Reminder.where(bot_id: @bot.id)%>
        <%= "Reminder " + i.to_s() + "- "+ reminder.reminder %>	
        <br>
        <% i = i + 1 %>
    <% end %>
    <% if Reminder.where(bot_id: @bot.id) == [] %>
        <span style = "color: #FF8C00;">Not Defined</span><%= image_tag('warning.png', size: "25", class: "mb-2") %>
    <% end %>      
</div>

app/views/bots/_bot_node_name.html.erb
<% if @node %>
    <div class = "text-center">
        <div class = "Bot-Response ml-3 mt-2 mb-1" >
            <span>
                <% if @node.name %>
                    <%= @node.name.truncate(20) %>
                <% else %>
                    <%= " Bot Response" %>
                <% end %>
                <%= link_to image_tag('edit.png', size: "17", class: "text-center mb-1", style: "margin-top: 0px;"), bot_node_name_edit_icon_click_path(@node.id), method: :get, remote: true  %>
            </span>
        </div>
    </div> 
<% end %>

app/views/bots/_bot_settings_completed.html.erb
<div class = "col-12 border container shadow p-5 bg-white" style = "margin-left: 17%;  margin-right: 0%;  margin-top: 15%; border: solid 1px #d5d5d5; border-radius: 5%; height: 600px;" >
    <h3 class = "mt-4">Bot Settings</h3>
    <br>
    <div class = "mt-4">
        <div id = "Outgoingnumber" class = "">
            <%=  render 'bots/Outgoingnumber' %>
        </div>
        <div id = "Botlanguage" class = "">
           <%= render 'bots/Botlanguage' %>
        </div> 
        <div  id = "Conversationstarter" class = "">    
            <%= render 'bots/Conversationstarter' %>
        </div>  
        <div  id = "Bottrigger" class = ""> 
            <%= render 'Bottrigger' %>
        </div>  
        <div  id = "NoCustomerResponse" class = "mt-0">   
           <%= render 'bots/NoCustomerResponse' %>
        </div>    
    </div>  
</div>

app/views/bots/_botnavigation.html.erb
<!--First navbar on compose message page-->
<nav class="navbar navbar-expand-lg" style = "background-color: #3b445b; color: #ebebeb; height: 55px;">
  <%= link_to '←', root_path, style: "font-size: 200%; color: #ebebeb; margin-top: -0.4%; text-decoration: none; margin-right: 1%;" %>
  <div class="nav-item" style = "margin-right: 1%;" >Referralyogi </div>
  <div class = "nav-item" style= "font-size: 140%; color: #ebebeb; margin-right: 1%;" >|</div>
  <div style = "margin-right: 1%;"><%= image_tag('bot.png', class: "rounded-circle", size: "30") %> </div>
  <% noid = "noid" + (@bot.id).to_s() %>
  <div id = "name"><%= @bot.name %></div>
  <div class = "col-2 hide" id = "nameform">
    <%= form_with scope: :botname, url: bot_path(@bot.id), method: :put,  remote: true do |f| %>
        <%= f.text_field :name, class: "text-center form_edit_name", placeholder:  @bot.name, id: noid  %>
    <% end %>
    </div>  
  <div> &nbsp;<%= image_tag('edit4.png', size: "25", class: "text-center mb-1", id: "edit")  %></div>
</nav>

<script type="text/javascript">
// show form
document.getElementById('edit').onclick = function() {
document.getElementById('name').classList.add('hide');
document.getElementById('nameform').classList.remove('hide');
}
</script>					

app/views/bots/_botsettings_reminder.html.erb
<% for reminder in Reminder.where(bot_id: @bot.id)%>
    <%= form_with scope: :botsettingsupdatereminder, url: reminders_update_botsettings_path(reminder.id), method: :get,  remote: true do |f| %>
        <%= text_area(:botsettingsupdatereminder, :reminder, cols: 40, rows: 3, class: 'container bg-white ml-3 reminder', value: reminder.reminder,  remote: true )%>
        <div class = "row mt-0" style = "margin-top: -20px;">
            <div class = "col-3 ml-3">
                <span style = "color: grey;"> Send After </span>
                <span class="mr-2 ml-4" style="width: 13px;"><%= select_minute(5, field_name: 'rebootconv', style: "background-color: #f7f2ed;") %></span>
                <span > min </span>
            </div>
            <div class = "col-1 text-right">
                <span id = "delete_reminder" class = "mt-0"> 
                <%= link_to image_tag('del.png', size: "20"), reminders_delete_botsettings_path(reminder.id), method: :delete, remote: true %>
                </span>
            </div>
            <%= f.submit "Update", class: "btn btn-success btn-sm" , style: "margin-left: 25px;" %> 
        </div>
    <% end %>
    <div class = "mt-4">  </div>
<% end %>

app/views/bots/_messages_area.html.erb
<!--New text message partial for user node -->
<% if @node %>
    <% send_message = "send_message" + (@node.id).to_s() %>
    <%# <%= javascript_include_tag  '//cdn.ckeditor.com/4.13.0/standard-all/ckeditor.js' %>   
    <%# <%= javascript_include_tag  '//localhost:3000/welcome/ckeditor' %> 
     
    <script src = "/assets/ckeditor/ckeditor.js" > </script> 
    
    <% ckeditorid = "ckeditor" + (@node.id).to_s() %>
    <div class="text-center mx-auto">
        <%= form_with scope: :text_messages, url:  messages_new_path(@node.id, @bot.id), method: :post, remote: true do |f|%>
        <div class="botresponses_messages_area_full mt-1">
            <%= text_area :text_messages, :text_message, cols: 30, rows: 4, id: ckeditorid %>
            <%# <%= cktext_area :text_messages, :text_message, cols: 30, rows: 4, ckeditor: { id: "cke" + ckeditorid, style: 'overflow-y: hidden;'}, style: 'background-color: #ebfddd; overflow-y: hidden;', id: ckeditorid   %>  
            <%= f.text_field :message_type, value: "text" , class: "hide"%>
            <div class="Path-484 ml-2 mb-1" style = "margin-top: -5px;"></div>
            <div class = "row">
                <div class = "col-6"></div>
                <div class = "col-1 mt-1" ></div>
                <div class = "col-1 mt-1"></div>
                <div class = "col-1"></div>
                <div class = "col-1"><%= image_submit_tag('send.png', class: "rounded-circle mt-1", style: "width: 25px;", id: send_message) %></div>
            </div>
        </div>
        <% end %>
    </div> 
<% end %>

<script type='text/javascript' charset='UTF-8'>
  
    CKEDITOR.replace( ('<%= ckeditorid %>'), {
        customConfig: "/assets/ckeditor/config.js"
    });
   

    
</script>

app/views/bots/_triggerphrases.html.erb
<!--Printing triggerphrases-->
<div class="container p-3" style="height: 85px; width: 400px; overflow-y: auto; overflow-x: hidden;" id = "style-4" >
    <% if Triggerphrase.where(bot_id: @bot.id) == [] %>
       <span class = "default-text" >This is the message which a user will enter, to<br> have a conversation with this bot.
        To add messages click on edit icon at the top right corner.</span>
    <% end %>
    <% for phrase in Triggerphrase.where(bot_id: @bot.id)%>
    <span class="triggerphrase ml-1 mr-1 mt-4 mb-4">
            <span class= "triggerfont ml-2 mr-2"><%= phrase.trigger %>
        <span class="hide mb-4" id= <%= "triggerphrase_delete" + (phrase.id).to_s%> >
        <%= link_to image_tag('cross.png', size: "10"), triggerphrase_destroy_path(phrase.id, @bot.id), method: :get, remote: true, class: ""%>	
        </span>		
    </span>	
    </span>  
    <% end %>
</div>

app/views/bots/_user_child_node_compressed.html.erb
<!--Compressed user child node-->
<% if child %>
<% user_child_node_message =  "user_child_node_message" + (child.id).to_s %>
<% expand =  "expand" + (child.id).to_s %>
<div class="row mb-2" id= <%= "child_compressed_id" + (child.id).to_s %> >
	<div class="connector_black_link"></div>
	<div class="usermessage_compressed_white_box rounded">
		<div class = "row text-center">
            <div class = "Bot-Response col-8 ml-3 mt-2 mb-1" id = <%= "childname" + (child.id).to_s %>>
                <% if child.name %>
                    <%= child.name %>
                <% else %>
                    Message from Customer 
                <% end %>
            </div>
            <div class = "mt-1 col-1" >
                <%= link_to image_tag('del.png', size: "17"), user_child_node_compressed_delete_path(child.id), method: :delete, data: { confirm: "All attached child nodes will be lost. Are you sure?" }, remote: true %>
            </div>
            <div class = "col-2 text-right" style = "padding-left: 5px; height: 25px; padding-top: -2px;">
                <%= link_to image_tag('expand.jpg', size: "14", class: "mt-2", id: expand), user_child_node_compressed_expand_path(child.id), method: :get, remote: true %>
            </div>
        </div> 
		<div class="child_divider mb-3"></div>
        <div id = <%= user_child_node_message %>>
            <div class="container m-1" style="height: 85px; width: 290px; overflow: auto;"  id = "style-1">
                <%= render 'bots/user_child_node_message', child: child, delete_message: false %>
            </div>
        </div>
	</div>
</div>

<% end %>

app/views/bots/_user_child_node_message.html.erb
<% if child %>
    <% if delete_message == true %>
        <div class="container border mt-1 p-1" style="height: 100px; width: 280px; overflow-y: auto; overflow-x: hidden; background-color: #F2F3F4; margin-top: 8px;" id = "style-4" >
            <% if Message.where(node_id: child.id) == [] %>
                <div class = "Node-text-font mt-2 p-3" style = "color: grey;" >No messages have been added yet. Go on and add the expected customer message.</div>
            <% else %>
                <% for message in Message.where(node_id: child.id)%>
                <span class="triggerphrase ml-1 mr-1 mt-4 mb-2">
                    <span class= "triggerfont ml-2 mr-2"><%= message.text_message %>
                        <span class="mb-4" id= <%= "user_child_delete_message" + (message.id).to_s%> >
                        <%= link_to image_tag('c.png', size: "8"), user_child_delete_message_path(message.id), method: :delete, remote: true, class: ""%>	
                    </span>		
                </span>	
                </span> 
                
                <% end %>
            <% end %>  
        </div>     
    <% end %>
    <% if delete_message == false %>
        <% if Message.where(node_id: child.id) == [] %>
        <div class = "Node-text-font mt-2 mb-1" >You have not added any messages yet. Click on expand icon and add messages first.</div>
        <% else %>
            <% for message in Message.where(node_id: child.id)%>    
            <span class="triggerphrase ml-1 mr-1 mt-4 mb-4">
                <span class= "triggerfont ml-2 mr-2"><%= message.text_message %></span>		
            </span>	
            </span> 
            
            <% end %>   
        <% end %>    
    <% end %>
<% end %>

app/views/bots/_user_child_node_name.html.erb
<% if child %>
    <div class = "text-center">
        <div class = "Bot-Response ml-3 mt-2 mb-1" >
            <span><% if child.name %></span>
                <%= child.name.truncate(20) %>
                <%= link_to image_tag('edit.png', size: "17", class: "text-center mb-1", style: "margin-top: 0px;"), user_child_node_name_edit_icon_click_path(child.id), method: :get, remote: true  %>
            <% end %>
        </div>
    </div> 
<% end %>

app/views/bots/_usermessagesmain_with_connector.html.erb
<!--Parent bot response and child user node connectors-->
<% if @node%>
    <% usermessagemain_partial = "usermessagemain_partial" + (@node.id).to_s%>
    <% connector_black_link_vertical = "connector_black_link_vertical" + (@node.id).to_s%>
    <% if @node.set_next_action == "add_a_node"%>
        <% number_of_child_nodes = 0%>
        <% for i in @node.children%>
            <% number_of_child_nodes = number_of_child_nodes + 1; %>
        <% end %>
        <% height = 52 + number_of_child_nodes * 52 %>
        <% height = height.to_s + "px" %>
        <div class="connector_black_circle" style = "margin-left: -9px;"></div>
        <div class="connector_black_link"></div>
        <div id= <%= connector_black_link_vertical %> style="margin-right: 15px; height:<%= height%>" class = "connector_black_link_vertical" ></div>	
        <div id= <%= usermessagemain_partial %>>
            <%= render 'bots/usermessagesmain'%> <!--Child user nodes-->
        </div>
    <% end %>
    <div>
        <div>
            <% for children in @node.children%>
                <div class="row">
                    <div class="Ellipse-160" style="margin-left: 30px;"></div>
                    <div class="Path-510" style="margin-right: 15px; "></div>
                    <div class="row" style="margin-bottom: 5px;">
                        <div id = <%= "botmessagemain_partial" + (children.id).to_s %>>
                            <%= render 'bots/botnode', parent_id: children.id %> <!--Bot response-->
                        </div>
                        <div class="row" id= <%= "usermessagemain_partial_with_connector" + (children.id).to_s %>> <!--Parent bot response and child user node connectors-->
                            <%= render 'bots/usermessagesmain_with_connector' %>	
                        </div>
                    </div>							
                </div>							
            <%end%>
        </div>			
    </div>
<% end %> 

app/views/bots/_usernode.html.erb
<!-- This is the first user messages node: Triggerphrase-->
<div class="Rectangle-827" id="triggerphrase_usermessage" >
  <span class = "row">
    <div class="col-2">
      
    </div>  
    <div class = "mt-2 col-7">
       Initial Message from Customer 
    </div>
    <div class = "col-2 mt-1 text-right submit-text hide"  id = "stop_edit">
      <%= link_to 'OK', triggerphrase_path(@bot.id), method: :patch, remote: true, style: "text-decoration: none; color: green;" %>
    </div> 
    <div class = "col-2 text-right mt-1 mb-2" >
      <%= link_to image_tag('edit.png', size: "18", id: "triggerphrase_edit_icon"), edit_triggerphrase_path(@bot.id), method: :get, remote: true %>		
    </div>
  </span>  
	<div class="Path-389"></div>
  <div id = "triggerphrases_partial"><%= render 'bots/triggerphrases'%></div>
	<div class="Path-389 mt-1 mb-1 hide" id="triggerphrase_usermessage_second_card_divider"></div>
	<div class="text-center mb-1 hide" id="triggerphrase_add_a_new_phrase" >
		<%= form_with scope: :triggerform, url: triggerphrase_create_path(@bot.id), method: :get, remote: true do |f| %>
      <span class="mx-auto text-center row">
       	<div class = "col-8 text-left ml-4 mr-0 p-0">
          <%= f.text_field :trigger, class: "form_trigger_trigger text-center", placeholder: "Add trigger words", remote: true, style: "width: 290px;", id: "addtriggerphrasefield" %> 
        </div>
        <div class = "col-3 text-right" , style= "padding-bottom: 0px; width: 10px; margin-top: -18px; height: 1px;" >
          <%= f.submit "Add", class: "submit-text mt-3", remote: true %>
        </div>
      </span>
    <% end %>
	</div>
</div>
									
									
										
							

app/views/bots/statistics.html.erb
statistics